Cyclic node equality implementation defined
yaml/yaml-spec pull request #114
Opened 2021-08-18 18:51 UTC by Thom1729

For #36.

It might be over-cautious to say that equality of *all* cyclic nodes is implementation-defined, but off the top of my head I can't think of a tighter criterion that's easy to understand.

2021-08-18 19:17 UTC, ingydotnet commented
Equality is complicated in YAML as there are many processing points to consider.

Take:
```
!seq : foo
!seq : bar
```
where `!seq` binds to a constructor binds to an iterator function returning for the sequence `1..`.

The tag and content are equal but the keys are guaranteed not to be.

Or
```
+: foo
+: bar
```

where an implicit resolver resolves to `!seq`.

I'd honestly like to see an addition to the effect that scalars tagged `tag:yaml.org,2002:*` with equal content are considered equal. For mapping keys that covers 99.99% of real world cases, likely.

2021-08-18 20:01 UTC, Thom1729 commented
In 1.2, those are unambiguous (the keys are equal). Equality is defined only for nodes in the representation graph. Construction creates native data structures that are inherently implementation-defined and may have their own notions of equality.

I can see the use case for autogenerated keys, but there's another difficulty with the example: mappings are unordered, so there's no reason that `foo` would get `1` and `bar` would get `2` rather than the other way around. The specifics might vary greatly depending on future details; the purpose of this PR is solely to clarify the limitations of the 1.2 spec. Since the 1.2 spec does unambiguously define equality for all non-cyclic documents, I think that relaxing it further would be a broader change than is necessary for this PR.

2021-08-29 12:14 UTC, eemeli requested changes
I think we should instead (or additionally?) define equality for alias nodes, which we're currently missing. As in:

```yaml
&foo []: x
*foo: y
```

Should those two keys be considered equal; is an alias equal to its source value? I don't think the spec is currently clear on this.

Also, rather crucially, the definition of "unique" is not explicitly linked to either concept of "equality" _or_ "identity". The first sentence of 3.2.1.3 does imply that it's connected with equality, but this really ought to be clarified:

> Since YAML mappings require key uniqueness, representations must include a mechanism for testing the equality of nodes.

2021-08-29 15:33 UTC, Thom1729 commented
Equality is only defined on nodes in the representation graph, which do not have anchors or aliases.

Good point on the definition of uniqueness. I think it's implied, but explicit is better than implied. I think I'll write up a separate PR for that.

2021-08-29 17:33 UTC, perlpunk approved these changes

2021-09-03 15:01 UTC, Thom1729 commented
@eemeli Is something that still needs to be addressed in this PR?

2021-09-05 06:59 UTC, eemeli approved these changes
After some further consideration, I'm happy with this change.

2021-09-13 15:36 UTC, ingydotnet requested changes

2021-09-13 15:36 UTC, ingydotnet commented on spec/spec.md
> +> If a node has itself as a descendant (via an alias), then equality of that node
maybe `…then determining the equality of…`

2021-09-13 15:44 UTC, Thom1729 commented on spec/spec.md
> +> If a node has itself as a descendant (via an alias), then equality of that node
Done.

2021-09-13 16:09 UTC, ingydotnet approved these changes

2021-09-13 20:16 UTC, ingydotnet commented
Applied as f65fe4e796e3d82b420482d2bb530ed10ff14cad

2021-09-13 20:16 UTC, closed without merging