[RFC] Split list of standard tags from list of recommended schemas.
yaml/yaml-spec pull request #140
Opened 2021-09-01 20:01 UTC by Thom1729

This PR removes all of the tag definitions from the chapter on schemas and puts them in a new chapter immediately before that one.

This is more of a discussion prompt than a fully-formed PR. I think that disentangling the tag definitions from the schema definitions may help to disentangle the concepts of resolution versus canonicalization and clarify what behavior is defined for a tag versus for a schema. I would like to do something like this for 1.3. My instinct is that it is out of scope for 1.2.1, but I could be convinced otherwise.

Feedback appreciated.

2021-09-13 16:17 UTC, Thom1729 commented
https://spec.yaml.io/pr-140/spec

2021-09-14 11:01 UTC, ingydotnet requested changes

2021-09-14 11:01 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +# Chapter #. Recommended Schemas
`# Appendix B, Recommended Schemas`

2021-09-14 11:03 UTC, ingydotnet commented
I assume you'll add Valid Formatted Content sections when 136 is merged.

2021-09-14 15:06 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +# Chapter #. Tag Repository
I tried this and all of the subheadings for the appendices were numbered 9.*n*, not A.*n* or B.*n*.

I'd definitely like to do this in 1.3, possibly also with the grammar itself. I don't think I care enough about it for now to mess with the section numbering code.

2021-09-14 15:06 UTC, Thom1729 commented
> I assume you'll add Valid Formatted Content sections when 136 is merged.

Yes.

2021-09-14 15:59 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +# Chapter #. Tag Repository
sounds good

2021-09-14 16:00 UTC, ingydotnet approved these changes

2021-09-14 21:12 UTC, perlpunk commented
I think I have the same issues with this as with #136.
If I'm the only one and all others agree, fine :)

2021-09-15 13:42 UTC, eemeli requested changes
While at this, we need to clarify the status of [yaml.org/type](https://yaml.org/type). We should leave this change out of the next spec release, and include it into the next one.

2021-09-20 18:47 UTC, closed without merging