Simplify favicon SVG.
yaml/yaml-spec pull request #142
Opened 2021-09-02 15:51 UTC by Thom1729

This should result in no visible change.

- Remove the IDs, which are unused.
- Remove the `version` attribute, which is deprecated.
- Remove the `height` and `width` attributes and the `<title>` element, which are useless for a favicon.
- Apply the red fill directly to the `A` path and remove the class/style.
- Remove the `translate` transformation and fix the path to work without it.

2021-09-02 16:12 UTC, Thom1729 commented
Published at https://spec.yaml.io/favicon/.

2021-09-02 21:43 UTC, ingydotnet requested changes

2021-09-02 21:43 UTC, ingydotnet commented on www/build/favicon.svg
> +  <polygon points="512 422.735 395.638 422.735 395.638 250.125 347.442 250.125 347.442 469.647 512 469.647 512 422.737 512 422.735" />
Can we add the `id='.'` attributes back and put the lines in Y A M L order?

2021-09-02 21:44 UTC, Thom1729 commented on www/build/favicon.svg
> +  <polygon points="512 422.735 395.638 422.735 395.638 250.125 347.442 250.125 347.442 469.647 512 469.647 512 422.737 512 422.735" />
We *could*. Why?

2021-09-02 21:45 UTC, ingydotnet commented on www/build/favicon.svg
> +  <polygon points="512 422.735 395.638 422.735 395.638 250.125 347.442 250.125 347.442 469.647 512 469.647 512 422.737 512 422.735" />
afaict, that's the only human indication of what each lines means.

2021-09-03 14:55 UTC, Thom1729 commented on www/build/favicon.svg
> +  <polygon points="512 422.735 395.638 422.735 395.638 250.125 347.442 250.125 347.442 469.647 512 469.647 512 422.737 512 422.735" />
Done.

2021-09-03 14:59 UTC, ingydotnet approved these changes

2021-09-03 20:40 UTC, merged