Fix JSON float regular expression and comment
yaml/yaml-spec pull request #159
Opened 2021-09-07 19:11 UTC by perlpunk

This reverts
24ec0f12f2ab30168185e563466292f6e51614fa
which was merged accidentally.

2021-09-08 13:48 UTC, eemeli approved these changes

2021-09-08 14:05 UTC, Thom1729 approved these changes

2021-09-08 20:16 UTC, perlpunk commented
I was actually expecting to get change requests :)
I'm wondering if I should link to json.org there.

2021-09-08 20:18 UTC, perlpunk commented
I did a small fix to the comment to actually quote the JSON regex, not the YAML one.

2021-09-08 22:59 UTC, ingydotnet requested changes

2021-09-08 22:59 UTC, ingydotnet commented on spec/spec.md
I would suggest changing this slightly to:
```
> Note: The regular expression for `float` does not exactly match the one in the
JSON specification; at least one digit is required after the dot: `( \. [0-9]+ )`.
The YAML 1.2 specification intended to match JSON behavior, but this cannot
be addressed in the 1.2.1 specification.
```

Note, use `make format` to make sure the changes wrap correctly.

2021-09-08 23:03 UTC, ingydotnet commented on spec/spec.md
Also note that the spec consistently use American English (not British English) forms for `ior` and `zation` suffixes (rather than `iour` and `sation`).

2021-09-10 22:02 UTC, perlpunk commented on spec/spec.md
> at least one digit is required after the dot

I find that sentence slightly ambiguous. Is it required in JSON or YAML?
Of course it gets obvious when looking at the table above, but not by looking at the sentence alone.
How about
"JSON specification, where at least one digit is required ..."

2021-09-11 13:37 UTC, ingydotnet commented on spec/spec.md
:+1:

2021-09-11 16:06 UTC, ingydotnet commented
I amended `Note: ...` to `> Note: ...` and merged

2021-09-11 16:06 UTC, closed without merging