Formally define production syntax.
yaml/yaml-spec pull request #183
Opened 2021-09-16 20:08 UTC by Thom1729

Provide a formal definition of the production syntax. Based in part on #158.

Special productions use the `<name>` syntax to distinguish them from normal productions.

Only a few comments remain — the 1024 character limit and the c-forbidden stuff.

Because alternation is defined to be greedy, and the quantifiers are all defined using alternation, the old text describing this is no longer necessary.

2021-09-16 20:10 UTC, Thom1729 commented
https://spec.yaml.io/pr-183

2021-09-16 21:52 UTC, ingydotnet requested changes

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  <empty>
Can we replace `<empty>` with `""` like in `e-scalar` ?

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  beginning at any prior point on the line and ending at the current position.
Wrong indent

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  * `<empty>`, which matches the empty string.
Maybe eliminate in favor of `""`. See below.

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  * `<start of line>`, which matches the empty string at the beginning of a
Any way to define this with a lookbehind?

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +* A sequence or alternation:
concatenation or alternation?

sequence is overloaded in spec, maybe.

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +`(a b) | (c d)`.
I'd rather not bother with this. We can be explicit with parens in the few places we need to be.

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  * `term+`, which matches `(term term*)`.
What happened to greedy?

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +Whitespace in productions is not significant except inside quoted strings.
Do we need to say this?

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +
Where is `{n}` quantifier?

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  * A quoted string (`"abc"`), which matches that sequence of characters.
Say quotes may use single or double form.

2021-09-16 21:52 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  <impossible>
Do we need impossible productions in the spec?

2021-09-16 21:56 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +  <empty>
We could; it's a matter of preference. I like `<empty>` because it's explicit and because my eyes get lost in `""`.

2021-09-16 21:59 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  <empty>
How about
```
s-indent(0) ::= ""    # Empty
```

I like `""` because it's concrete, and we have one less "special"

2021-09-16 21:59 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +  * `<start of line>`, which matches the empty string at the beginning of a
Probably, but it might be a bit complicated because we don't want to match the middle of a CRLF. Also, we'd like to eliminate the existing lookbehind (in 1.3 if not in 1.2.2) but I'm not sure we could eliminate the start-of-line symbol.

2021-09-16 21:59 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +`(a b) | (c d)`.
I think this would add a lot of otherwise-unneeded parens. But I'll take a look at the productions.

2021-09-16 22:02 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +  * `term+`, which matches `(term term*)`.
Alternation is defined to prefer the first branch, so these are greedy by the way they're defined. E.g. `(<empty> | term)` would be lazy.

2021-09-16 22:03 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +Whitespace in productions is not significant except inside quoted strings.
Arguably not, but I think it's inoffensive at worst.

2021-09-16 22:03 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +
It doesn't exist anymore since s-indent was redefined.

2021-09-16 22:07 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +  <impossible>
Yes, at least as currently written, for two reasons:

- n can be -1, which makes all the indentation productions impossible.
- `s-indent-less-than(0)` is impossible. We can actually eliminate `s-indent-less-than(n)` and replace it everywhere with `s-indent-less-or-equal(n+1)`, but that would mean removing a production.

In 1.3, when we fix the -1 thing, we won't need it anymore.

2021-09-17 10:01 UTC, eemeli approved these changes
Looks good. Would prefer avoiding spaces within terms, hence the suggestions renaming `<start-of-line>` and `<end-of-input>`.

2021-09-17 10:02 UTC, eemeli commented on spec/1.2.2/spec.md
> +  * A quoted string (`"abc"`), which matches that sequence of characters.
Is there a reason to allow for single quotes in term definitions?

2021-09-17 10:03 UTC, eemeli commented on spec/1.2.2/spec.md
> +`(a b) | (c d)`.
I would have a strong preference for explicitly including the order of operations.

2021-09-17 10:05 UTC, eemeli commented on spec/1.2.2/spec.md
> +  <empty>
I would prefer `<empty>`. If/as it looks like `""` would need an explanatory comment, it ought to instead have a name that avoids the issue.

2021-09-17 14:15 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  * A quoted string (`"abc"`), which matches that sequence of characters.
They read cleaner and are useful for defining `'"'` cleanly.

They also have strong 'character' type semantics in some languages.

I added the concept of double quotes to not need: `'Y' 'A' 'M' 'L'` stuff but I'm not keen on collapsing to double quotes for everything just because we can.

2021-09-17 14:21 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  <impossible>
I still don't get it. I understand that the productions you added with `<impossible>` _are_ impossible.
But that's obvious from the series terminating productions next to them.

Can you show me an example of a YAML stream where a parser would reach those productions?

2021-09-17 14:36 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +    `term-two` otherwise.
Agree and already refactored.

2021-09-17 14:36 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  * `<end of input>`, matches the empty string at the end of the input.
Thom and I both did.

2021-09-17 14:40 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +
:+1:

2021-09-17 14:41 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  * `term+`, which matches `(term term*)`.
I think it's worth adding a note here.

2021-09-17 14:42 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +* A sequence or alternation:
updated

2021-09-17 14:42 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  beginning at any prior point on the line and ending at the current position.
fixed

2021-09-17 14:42 UTC, ingydotnet commented on spec/1.2.2/spec.md
> +  <empty>
ok

2021-09-17 15:44 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +  <impossible>
It's a consequence of the definition. If we say that *n* can be either a natural number or -1, then `s-indent(n)` should be defined for -1.

If we want to omit the impossible productions, we'll have to add a special note that for those productions, *n* may not be -1 (or zero in the case of `s-indent-less-than`).

2021-09-17 15:52 UTC, Thom1729 commented on spec/1.2.2/spec.md
> +> Note: Quantified terms are always greedy and do not have the backtracking
The quantifiers as defined are greedy, but not possessive. E.g., `"a"* "a"` would match the string `a`.

2021-09-17 19:07 UTC, ingydotnet approved these changes
Love it

2021-09-17 19:09 UTC, merged