Use standard markdown table format
yaml/yaml-spec pull request #306
Opened 2023-04-11 16:36 UTC by killermoehre

* Description of changes:

Markdown tables with all necessary sides set render prettier, as there is no ambiguity about the cell content and the border.

By submitting this pull request, I confirm that you can use, modify, copy, and
redistribute this contribution, under the terms of your choice.

2023-04-11 18:17 UTC, KrazyKrazy8 reviewed
#304

2023-04-14 22:45 UTC, Dimiturpenev approved these changes

2023-04-14 22:50 UTC, Dimiturpenev approved these changes

2023-05-23 13:40 UTC, eemeli requested changes
In this case, the style recommended by Prettier is not in fact prettier. Forcing the columns to match the longest contents makes them significantly longer and therefore line-wraps them, reducing the legibility of the source.

Also, the resulting HTML is the same, so this has no effect on the published spec.

2025-08-28 00:36 UTC, cokybit approved these changes

2026-04-23 00:04 UTC, marekdkropiewnicki-dotcom approved these changes

2026-04-23 00:46 UTC, closed without merging