Add a "License" file to the repository
yaml/yaml-spec pull request #95
Opened 2021-07-31 14:07 UTC by ingydotnet

This is simply the Copyright text that appears at the front of the spec.

2021-08-06 09:02 UTC, eemeli requested changes

2021-08-06 09:02 UTC, eemeli commented on License
> +This document may be freely copied, provided it is not modified.
```suggestion
```

I don't think we should include this here, as outside of the compiled spec it's unclear what "this document" really means.

At a first glance, it would seem that we might want to use [CC-BY-ND](https://creativecommons.org/licenses/by-nd/2.0/) as a license, but I'm not sure if there are considerations that I'm not taking into account here.

2021-10-02 11:37 UTC, ingydotnet commented
I'm closing this for now.

2021-10-02 11:37 UTC, closed without merging

2022-02-28 19:44 UTC, jcflack commented
I'm adding a comment to this issue just to connect it to yaml/yaml-reference-parser#1, given that the issues are kind of inseparably connected.